# Writes docs/symbols.md: every method of src/threatinc (and its rules package) with its line and the
# first sentence of its javadoc, so "where is X decided" is one grep. Run by compile.ps1; never edit the output.
use strict;
use File::Basename;
use File::Spec;

my $root = dirname(dirname(File::Spec->rel2abs($0)));
my @files = sort(glob("\"$root/src/threatinc/*.java\""), glob("\"$root/src/threatinc/rules/*.java\""));
my %skip = map { $_ => 1 } qw(return new else if for while switch catch throw do try case synchronized);

my $out = "# Symbol index (generated by tools/gen-symbols.pl at every build - do not edit, do not read whole: grep it)\n\n"
	. "One line per method: `Class.method(params)` :line - first sentence of its javadoc. `###` lines are the\n"
	. "section banners inside a class. Grep a word of the behaviour (\"landing\", \"bounty\", \"upkeep\") or a symbol.\n";
my $methods = 0;

for my $file (@files) {
	open(my $f, '<:raw', $file) or die "$file: $!";
	my @lines = <$f>;
	close $f;
	s/\r?\n$// for @lines;
	my $class = basename($file, '.java');
	$class = "rules.$class" if $file =~ m{/rules/};
	$out .= "\n## $class (" . scalar(@lines) . " lines)\n";
	my ($doc, $inDoc, $docEnd) = ('', 0, -9);
	for (my $i = 0; $i < @lines; $i++) {
		my $l = $lines[$i];
		if ($inDoc) {
			if ($l =~ m{^(.*?)\*/}) { $doc .= ' ' . $1; $inDoc = 0; $docEnd = $i; }
			else { $doc .= ' ' . $l; }
			next;
		}
		if ($l =~ m{^\s*/\*\*(.*)$}) {
			my $rest = $1;
			if ($rest =~ m{^(.*?)\*/}) { $doc = $1; $docEnd = $i; }
			else { $doc = $rest; $inDoc = 1; }
			next;
		}
		# a banner: a rule of dashes or equals, then a titled comment
		if ($l =~ m{^\s*//\s*[-=]{8,}\s*$} && $i + 1 < @lines && $lines[$i + 1] =~ m{^\s*//\s*([A-Za-z].*?)\s*$}) {
			$out .= "### $1\n";
			next;
		}
		next if $l =~ m{^\s*(//|\*|@)};
		my $head = $l;
		$head =~ s/\(.*$//;
		next unless $l =~ /\(/ && $head !~ /=/;
		my ($name, $ok);
		if ($head =~ /^\s+(?:(?:public|private|protected|static|final|synchronized|abstract)\s+)+(?:<[^>]+>\s+)?(?:[\w<>\[\],.?]+\s+)?(\w+)\s*$/) {
			$name = $1; $ok = 1;
		} elsif ($head =~ /^\t([\w<>\[\],.?]+)\s+(\w+)\s*$/ && !$skip{$1} && $l =~ /\{\s*$/) {
			$name = $2; $ok = 1;
		}
		next unless $ok && !$skip{$name};
		# the signature may run over several lines
		my $sig = $l;
		my $j = $i;
		while ($sig !~ /\)/ && $j + 1 < @lines && $j < $i + 6) { $sig .= ' ' . $lines[++$j]; }
		next if $sig =~ /\)\s*;\s*$/ && $sig !~ /abstract/;
		my ($params) = $sig =~ /\((.*?)\)/;
		$params = '' unless defined $params;
		$params =~ s/\s+/ /g;
		$params =~ s/^\s+|\s+$//g;
		my $note = '';
		if ($docEnd >= $i - 3 && $doc ne '') {
			my $d = $doc;
			$d =~ s/\s*\*\s+/ /g;
			$d =~ s/\{\@\w+\s+([^}]*)\}/$1/g;
			$d =~ s/<[^>]+>//g;
			$d =~ s/\s+/ /g;
			$d =~ s/^\s+|\s+$//g;
			$d = $1 if $d =~ /^(.*?[.:;])\s/;
			$d = substr($d, 0, 200);
			$note = " - $d" if $d ne '';
		}
		$out .= "- `$class.$name($params)` :" . ($i + 1) . "$note\n";
		$methods++;
		$doc = '';
		$docEnd = -9;
	}
}

open(my $o, '>:raw', "$root/docs/symbols.md") or die $!;
print $o $out;
close $o;
print "docs/symbols.md: $methods methods in " . scalar(@files) . " classes\n";
